### ISSUE TITLE
pdf format not recognised by preview

### ISSUE THREAD

**Issue by AlvaroR156** [ohoachuck/wwdc-downloader#18]
Cannot open the pdf. 
Message error:
"It may be damaged or use a file format that Preview doesn’t recognize."

**Comment by AlvaroR156** [comment]
If you want to update, I found this one working good.
curl https://developer.apple.com/videos/wwdc/2014/ \
| grep -iIoh 'http.*pdf?dl=1' \
| sed -e 's/\?dl=1//g' \
| xargs -n1 curl --remote-name

Origin: http://samwize.com/2014/06/06/download-all-wwdc-2014-pdf-slides-only/

**Comment by AlvaroR156** [comment]
this works
curl https://developer.apple.com/videos/wwdc/2014/ | grep -iIoh '|.*http.*._sd_.*dl=1' | sed -e 's/|.*"//g' | sed -e 's/\?dl=1//g'|xargs -n1 curl --remote-name

**Comment by ohoachuck** [comment]
fixed in latest version
