### ISSUE TITLE
List of Videos

### ISSUE THREAD

**Issue by AndreiVidrasco** [ohoachuck/wwdc-downloader#19]
It's no way to see full list of video for previous years
Command
./wwdcVideoPDFGet-curlVersion.sh -y 2014 -L

starts downloading

**Comment by ohoachuck** [comment]
Hello thanx for your comment.
Indeed I have added this to 2015 but did not reflect the changes to previous years. This have been fixed in the latest commit.
You might want to get the update and download again to grab sample codes.
