### ISSUE TITLE
Hard coded home directory should be replace by a tilde 

### ISSUE THREAD

**Issue by jduquennoy** [ohoachuck/wwdc-downloader#21]
WWDC_DIRNAME is defined using an absolute path to the user directory.
While this is valid in most of the cases, it causes problems when a custom user directory has been defined.
/Users/${USER} should be replaced by '~', that will expand to the home directory defined in the user profile.

Thanks for that script, it was very handy !

**Comment by ohoachuck** [comment]
Hello,
thanx for your comment. I have fixed this in the lastest commit.
I have used $HOME in stead of ~ that potentially could cause problems I believe.
