### ISSUE TITLE
PDF for wwdc 2015 are not downloaded

### ISSUE THREAD

**Issue by ignazioc** [ohoachuck/wwdc-downloader#22]
Instead of the PDF file, a 16byte file is created with the right name like `217 - Adopting New Trackpad Features.pdf` and the content is `File not found."`

**Comment by ohoachuck** [comment]
Sorry, I did the script in the hurry (quick and dirty mode) then did not had really time to check all modes. It appears that PDFs wasn't downloaded correctly in -f SD (default) mode.
I have just fixed it now and committed changes. You can safely re-run the script and it should update PDFs files (al least I hope ;) ).

**Comment by ohoachuck** [comment]
Make sure you get the very last commit. As I first fixed 2015 committed and realised it was also there for 2014. then fixed and committed again.

**Comment by Rido** [comment]
I just tried to download the WWDC 2015 HD videos and the videos are working fine! But I got the same issue with the PDF files. They're 16 bytes and I can't open them.
The command that I used is: `./wwdcVideoPDFGet-curlVersion.sh -f HD`

**Comment by iamioannis** [comment]
Same here. Just download the latest commit and PDFs are indeed not opening from preview and other PDF reading apps.

Once again we all can't thank you enough for your work 😊

**Comment by ignazioc** [comment]
Version 1.8.7 works well for me. Just be sure to download the last version and remove the broken files from the PDFs folder.

**Comment by iamioannis** [comment]
Do you use any options when running the command?

**Comment by Rido** [comment]
I get the following output for all the PDF files:

```
downloading PDF doc for session 219: Mysteries of Auto Layout, Part 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16  100    16    0     0     30      0 --:--:-- --:--:-- --:--:--    30
```

I'm using the latest version.

**Comment by iamioannis** [comment]
Same here. 
Here is the command I'm running
```
 wwdcVideoPDFGet-curlVersion.sh -v -f HD -o <PATH>
```

**Comment by ignazioc** [comment]
I'm not using any switch, just
    wwdcVideoPDFGet-curlVersion.sh
