### ISSUE TITLE
Some Sample Code not downloading properly

### ISSUE THREAD

**Issue by jchas** [ohoachuck/wwdc-downloader#23]
Most of the sample code downloads properly, but some don't.

For instance, 226 - Advanced NSOperations.zip only appears as a 2 kB download that is empty.

Ditto for 217 - AlignmentGuides - AppKit Haptic Feedback Filtering using NSAlignmentFeedbackFilter, although 217 - ForceTouchCatalog - Using the Force Touch Trackpad API downloads fine.

**Comment by eytanbiala** [comment]
+1

**Comment by botsmack** [comment]
+1

**Comment by alemar11** [comment]
broken .zip list:
208 - Lister (for watchOS, iOS, and OS X).zip
208 - WatchKitAudioRecorder - Audio Recording and Playback.zip
217 - AlignmentGuides - AppKit Haptic Feedback Filtering using NSAlignmentFeedbackFilter.zip	
226 - Advanced NSOperations.zip
405 - Exploring San Francisco.zip
408 - Crustacean.zip
411 - DemoBots - Building a Cross Platform Game with SpriteKit and GameplayKit.zip
607 - MetalKitEssentials - Using the MetalKit View, Texture Loader, and Model I-O.zip
714 - PotLoc - CoreLocation with iPhone and Apple Watch.zip
714 - Footprint - Indoor Positioning with Core Location

710 - CloudKit Catalog - An Introduction to CloudKit (Cocoa and JavaScript).zip (redirect to https://cdn.apple-cloudkit.com/cloudkit-catalog/)

**Comment by machackx** [comment]
+1

**Comment by ohoachuck** [comment]
Video location and Apple html pages have moved, so I started over from crash with a new script (in Swift) that should be improved in the next few days. I'll have to include Sample code also. 
So I'll close this issue as not really applicable anymore.

Thanx for having shared this (and sorry for late reply).
