### ISSUE TITLE
HD PDFs aren't downloading correctly. Here's the fix.

### ISSUE THREAD

**Issue by botsmack** [ohoachuck/wwdc-downloader#25]
I noticed that when choosing HD, the PDFs were not downloading correctly. Looks like around line 650 the "pdfURL" variable is getting set twice with the SD version winning out. But there's no "`_sd_`" pattern to remove in the HD version. As a result, the PDF link generated is invalid.

You can replace those two "pdfURL" commands with this one:

    pdfURL=`echo ${videoURL} | sed 's/_'${LC_FORMAT}'_/_/g' | sed 's/\.mp4/\.pdf/g'`

**Comment by CAPIStkidd** [comment]
+1

**Comment by nnhubbard** [comment]
+1

**Comment by ohoachuck** [comment]
Thank you guys for pointing this out. 
Special thanks to Richard for the fix; I have just committed it.
