### ISSUE TITLE
No checking on partial download

### ISSUE THREAD

**Issue by weyhan** [ohoachuck/wwdc-downloader#26]
I have hit an issue where a lot of the files (videos and sample code) did not complete download but the script will move the ".download" partial files to the final filename. Not sure if it is apple's side or my ISP being flakey but the issue remains that the script should check curl's exit status before moving the part file to the final filename.

The fix is simple and I have fixed it on my forked version. Can I make a pull request to include my fixes?

**Comment by ohoachuck** [comment]
Good point,
I have to admit, I can't see sea surface since back from wwdc (meaning badly busy). It would be much easier for me if you propose a pull request. After all this is the all point of opening the code to all.
Please do so.

O.

Envoyé de mon iPhone

**Comment by ohoachuck** [comment]
Thanks, it have been merged.
