### ISSUE TITLE
Broken on ElCapitain?

### ISSUE THREAD

**Issue by sanguish** [ohoachuck/wwdc-downloader#36]
Seems like the downloader is broken on El Capitain. Seems like maybe /tmp can't be written to?

```
Mac-mini:NewWWDC2015 sanguish$ ./wwdcVideoPDFGet-curlVersion.sh -f HD

Using 'no password' mode (this is possible since WWDC 2014 sessions addition)!
try using -l option if download does not work.

sed: /tmp/wwdc-session-10E7EB69-D9A8-4B8C-ADA8-969005B8A4C8.tmp/titles.txt: No such file or directory
mv: rename /tmp/wwdc-session-10E7EB69-D9A8-4B8C-ADA8-969005B8A4C8.tmp/titles.txt to /tmp/wwdc-session-10E7EB69-D9A8-4B8C-ADA8-969005B8A4C8.tmp/titles-to-be-escaped.txt: No such file or directory
sed: /tmp/wwdc-session-10E7EB69-D9A8-4B8C-ADA8-969005B8A4C8.tmp/titles-to-be-escaped.txt: No such file or directory
########## DOWNLOADING HD VIDEOS and PDFs files ##########
Mac-mini:NewWWDC2015 sanguish$ 
```

**Comment by Piyush08** [comment]
@ohoachuck  I am also facing the same issue when I try to download SD videos. **Help me**

**Comment by FaisalCs** [comment]
Yeah. I have the same issue. could you fix please. We will get so much benefit from using that awesome script. thanks a lot 😄

**Comment by rokjarc** [comment]
I can't try this today but i believe this could be solved (a workaround actually) by temporarily disabling "System IntegrityProtection". Details here: http://stackoverflow.com/a/33294403/653513

**Comment by curno** [comment]
I had tried turning of the integrity protection, didn't work :(

Would you please fix this sometime? It will be very helpful.

**Comment by FaisalCs** [comment]
You can use this application. It does the same thing. You can download all WWDC since 2011 from it. 

https://github.com/insidegui/WWDC

Best of luck

**Comment by curno** [comment]
Thank you, it's very helpful.

**Comment by prefrontal** [comment]
I ran into the same problem this evening.  It looks like Apple has moved the content to a new page and has changed the page format.  I was able to point it back at the right WWDC 2015 page, but the script can't parse the content at the moment.  :(

**Comment by ohoachuck** [comment]
Previous bash version is not maintained anymore. Started from scrash on a Swift version.
