### ISSUE TITLE
How to use this script?

### ISSUE THREAD

**Issue by jeetendra-choudhary** [ohoachuck/wwdc-downloader#47]
How exactly this script is supposed to be used? I did try to use it in terminal by the command and got command not found error.

`$ wwdc2016.swift --hd
-bash: wwdc2016.swift: command not found
`

Thanks

**Comment by chandanankush** [comment]
swift[space]wwdc2016.swift [options]     
                   
        swift wwdc2016.swift --hd

**Comment by jeetendra-choudhary** [comment]
Thank you it worked. Thanks a lot.
