### ISSUE TITLE
Additional video size other than SD and HD

### ISSUE THREAD

**Issue by weyhan** [ohoachuck/wwdc-downloader#83]
Apple only provide two official video size for download. SD is 640p and HD is 720p. However, the embedded player will serve you up to 1080p if bandwidth allows. It's downloadable with a few extra steps and nothing difficult to download them.

I'm not sure if there are any interest in getting the higher resolution. If there is, I would consider working on adding into the scripts.

Please let me know.

**Comment by ohoachuck** [comment]
I think it might be useful for those that bulk download all the video on an extra storage for later view on Tv. This said current script only work for Mac OS formated external storage. I’m not sure if this is compatible with most media players out there. 
To me if you feel like doing it, it’s still valuable for everyone. I personally would use the 1080p if available! 😜
I would be flab if you feel doing it !

Olivier.

**Comment by weyhan** [comment]
It’s still just mp4 sliced up into small chunks for streaming. File extension is .ts. All that is needed is to concat them together. 

I’ll make a pull request when I get it done. 😉

**Comment by weyhan** [comment]
@ohoachuck I've a preliminarily version working. However, the ts file slices concat together is playable on files without conversion is still basically a streaming format. Playback is fine but seeking will be bad. Adding a process to convert to a mp4 container increases the file size to almost double and the conversion time can be long, especially for the longer video like the keynote. What's your opinion? Is it still desirable?

**Comment by ohoachuck** [comment]
I think as long as you already have put some effort in it (in top of getting this as a personal exploration), it worth pushing it as an option. In addition there are always people out there that might want to vision this on a big screen. At least for next year sessions (if not this year) were more and more dev team take WWDC occasion to organize a get together local watching event with small time shift after the real event. In a big screen.
It’s becoming harder and harder to get there (@WWDC) but it still worth freeze a full week for iOS dev teams to watch time shifted sessions together as if there were there.

If it’s not too much to close this. I would say go for it. 
And thanks you for your time on this.

O.
Envoyé de mon iPhone

**Comment by weyhan** [comment]
I still have some ways to go but I won't want to let my work so far go to waste. There are a few things missing like resume after internet interruption. Because the way to download from the stream is very different, if I find that it's not possible to add it into your script without making your script a mess, I'll contribute a separate script for downloading from stream if that's ok with you.

**Comment by ohoachuck** [comment]
Of course that’s ok, and probably simpler for start.

O.

Envoyé de mon iPhone

**Comment by weyhan** [comment]
The progress is coming along very well. I have some edge cases to take care of and then wired up the options to customize what and how to download the stream. I expect to have pull request some time after another weekend of working on it.

It’ll be a new file for now. When I have the time later, I’ll integrate them to the main file later if it’s not going to complicate the scripts.

**Comment by weyhan** [comment]
Currently the version from my pull request is working well except some videos may have their intermediary files not cleanup. If anyone is using this version, you may have to cleanup those files manually. To do the cleanup manually, just trash the directory with the ".part" suffix when the download and encoding is done.

**Comment by ohoachuck** [comment]
I don't know if I did thank you enough for the massive work done for getting streamed videos.
Thanks again.

O.

**Comment by weyhan** [comment]
You're welcome but I wanted the streaming video just as bad. Also, I enjoy working on something other than work once in a while. ;)
